export MYSQL_INSTANCE=
export MYSQL_UNIX_SOCKET="/cloudsql/$MYSQL_INSTANCE"
export MYSQL_PASSWORD=
export MYSQL_USER=
export MYSQL_DATABASE=
export MYSQL_HOST=
export MYSQL_PORT=

export POSTGRES_INSTANCE=
export POSTGRES_UNIX_SOCKET="/cloudsql/$POSTGRES_INSTANCE"
export POSTGRES_PASSWORD=
export POSTGRES_USER=
export POSTGRES_DATABASE=
export POSTGRES_HOST=
export POSTGRES_PORT=

export SQLSERVER_INSTANCE=
export SQLSERVER_PASSWORD=
export SQLSERVER_USER=
export SQLSERVER_DATABASE=
export SQLSERVER_HOST=
export SQLSERVER_PORT=
