runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1

# [START env_variables]
env_variables:
  TWILIO_ACCOUNT_SID: your-account-sid
  TWILIO_AUTH_TOKEN: your-auth-token
  TWILIO_NUMBER: your-twilio-number
# [END env_variables]
