assign_issues_by:
- labels:
  - 'api: routeoptimization'
  to:
  - bshi
- labels:
  - "api: asset"
  to:
  - GoogleCloudPlatform/cloud-asset-analysis-team
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: storage'
  - 'api: storagetransfer'
  to:
  - tritone
- labels:
  - 'api: bigquery'
  - 'api: bigqueryconnection'
  - 'api: bigquerydatatransfer'
  - 'api: bigqueryreservation'
  - 'api: bigquerystorage'
  - 'api: datacatalog'
  to:
  - shollyman
- labels:
  - 'api: dataproc'
  to:
  - bradmiro
- labels:
  - 'api: logging'
  - 'api: clouderrorreporting'
  to:
  - GoogleCloudPlatform/observability-devx
- labels:
  - 'api: pubsub'
  to:
  - hongalex
- labels:
  - 'api: spanner'
  to:
  - rahul2393
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/cloud-sql-connectors
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - "api: parametermanager"
  to:
  - GoogleCloudPlatform/cloud-parameters-team
- labels:
  - "api: modelarmor"
  to:
  - GoogleCloudPlatform/cloud-modelarmor-team  
- labels:
  - "api: secretmanager"
  to:
  - GoogleCloudPlatform/cloud-secrets-team
- labels:
  - "api: securitycenter"
  to:
  - GoogleCloudPlatform/gcp-security-command-center

assign_prs_by:
- labels:
  - "api: asset"
  to:
  - GoogleCloudPlatform/cloud-asset-analysis-team
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/cloud-sql-connectors
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - "api: secretmanager"
  to:
  - GoogleCloudPlatform/cloud-secrets-team
- labels:
  - "api: parametermanager"
  to:
  - GoogleCloudPlatform/cloud-parameters-team
- labels:
  - "api: modelarmor"
  to:
  - GoogleCloudPlatform/cloud-modelarmor-team  
- labels:
  - "api: securitycenter"
  to:
  - GoogleCloudPlatform/gcp-security-command-center