assign_issues_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  - 'api: storage'
  to:
  - tritone
- labels:
  - 'api: bigquery'
  to:
  - shollyman
- labels:
  - 'api: dataproc'
  to:
  - bradmiro
- labels:
  - 'api: pubsub'
  to:
  - hongalex
- labels:
  - 'api: run'
  to:
  - grayside
- labels:
  - 'api: spanner'
  to:
  - skuruppu
