assign_issues_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - crwilcox
- labels:
  - 'api: storage'
  to:
  - tritone
- labels:
  - 'api: bigquery'
  - 'api: bigqueryconnection'
  - 'api: bigquerydatatransfer'
  - 'api: bigqueryreservation'
  - 'api: bigquerystorage'
  - 'api: datacatalog'
  to:
  - shollyman
- labels:
  - 'api: dataproc'
  to:
  - bradmiro
- labels:
  - 'api: logging'
  - 'api: clouderrorreporting'
  to:
  - nicoleczhu
- labels:
  - 'api: pubsub'
  to:
  - hongalex
- labels:
  - 'api: run'
  to:
  - grayside
- labels:
  - 'api: spanner'
  to:
  - skuruppu
