runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

env_variables:
  CLOUDSQL_CONNECTION_NAME: your-connection-name
  CLOUDSQL_USER_NAME: your-user-name
  CLOUDSQL_PASSWORD: your-password

