runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1

# [START gae_flex_golang_redis_yaml]
env_variables:
  REDIS_ADDR: "<REDIS_HOST>:<REDIS_PORT>"
  REDIS_PASSSWORD: ""
# [END gae_flex_golang_redis_yaml]
