# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: go
api_version: go1

handlers:
# [START gae_go_env_static_handlers]
# If the path is empty, show static index.html file
- url: /
  static_files: index.html
  upload: index.html

# Otherwise, find file in static directory
- url: /static
  static_dir: static
# [END gae_go_env_static_handlers]  
- url: /.*
  script: _go_app
