runtime: go
api_version: go1

handlers:
// [START static_handlers]
# If the path is empty, show static file index.html
- url: /
  static_files: index.html
  upload: index.html
  
# Otherwise, find file in static-files directory
- url: /static
  static_dir: static-files
// [END static_handlers]  
- url: /.*
  script: _go_app
