runtime: go
env: flex
api_version: go1

env_variables:
  OAUTH2_CALLBACK: https://<your-project-id>.appspot.com/oauth2callback

# [START cloudsql_settings]
# Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
# For SQL v2 instances, this should be in the form of "project:region:instance".
# Cloud SQL v1 instances are not supported.
#
# This should match the value in config.go
beta_settings:
#  cloud_sql_instances: INSTANCE_CONNECTION_NAME
# [END cloudsql_settings]
