runtime: go
vm: true

automatic_scaling:
  min_num_instances: 1

#[START env]
env_variables:
  # See https://github.com/go-sql-driver/mysql
  MYSQL_CONNECTION: user:password@tcp(127.0.0.1:3306)/dbname
#[END env]

#[START cloudsql_settings]
# Replace INSTANCE_CONNECTION_NAME with the value obtained  when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
beta_settings:
    cloud_sql_instances: INSTANCE_CONNECTION_NAME
#[END cloudsql_settings]
