# An example API configuration.
#
# Below, replace YOUR_PROJECT_ID with your Google Cloud Project ID.

# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

# Name of the service configuration.
name: hellogrpc.endpoints.YOUR_PROJECT_ID.cloud.goog

# API title to appear in the user interface (Google Cloud Console).
title: Hello gRPC API
apis:
- name: helloworld.Greeter
