// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package ping

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Pong struct {
	Index                int32                `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ReceivedOn           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=received_on,json=receivedOn,proto3" json:"received_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Pong) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Pong) GetReceivedOn() *timestamp.Timestamp {
	if m != nil {
		return m.ReceivedOn
	}
	return nil
}

type Response struct {
	Pong                 *Pong    `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPong() *Pong {
	if m != nil {
		return m.Pong
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "ping.Request")
	proto.RegisterType((*Pong)(nil), "ping.Pong")
	proto.RegisterType((*Response)(nil), "ping.Response")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x31, 0xa4, 0x14, 0x2e, 0x2a, 0x83, 0xc5, 0x10, 0x65, 0x80, 0x2a, 0x0c, 0x44, 0x0c,
	0x2e, 0x84, 0x91, 0x87, 0xa0, 0x72, 0xd8, 0x51, 0xda, 0x1c, 0x96, 0x25, 0x72, 0x36, 0xb1, 0x5b,
	0xf1, 0xf8, 0x28, 0x76, 0x2c, 0xc1, 0xc4, 0xf8, 0x9f, 0xbf, 0x3b, 0x7f, 0x3f, 0xac, 0x06, 0x74,
	0xae, 0x53, 0x28, 0xec, 0x68, 0xbc, 0xe1, 0x99, 0xd5, 0xa4, 0xca, 0x5b, 0x65, 0x8c, 0xfa, 0xc4,
	0x4d, 0x98, 0xed, 0x0e, 0x1f, 0x1b, 0xaf, 0x07, 0x74, 0xbe, 0x1b, 0x6c, 0xc4, 0xaa, 0x3b, 0x58,
	0x4a, 0xfc, 0x3a, 0xa0, 0xf3, 0xbc, 0x80, 0xe5, 0x7c, 0xa2, 0x60, 0x6b, 0x56, 0x5f, 0xca, 0x14,
	0x2b, 0x07, 0xd9, 0xd6, 0x90, 0xe2, 0xd7, 0xb0, 0xd0, 0xd4, 0xe3, 0x77, 0x78, 0x5f, 0xc8, 0x18,
	0x7e, 0xef, 0x9d, 0xfe, 0xd9, 0xe3, 0x2f, 0x90, 0x8f, 0xb8, 0x47, 0x7d, 0xc4, 0xfe, 0xdd, 0x50,
	0x71, 0xb6, 0x66, 0x75, 0xde, 0x94, 0x22, 0x3a, 0x89, 0xe4, 0x24, 0xde, 0x92, 0x93, 0x84, 0x84,
	0xbf, 0x52, 0xf5, 0x00, 0x17, 0x12, 0x9d, 0x35, 0xe4, 0x90, 0xdf, 0x40, 0x66, 0x0d, 0xa9, 0xf0,
	0x6f, 0xde, 0x80, 0x98, 0xba, 0x89, 0x49, 0x49, 0x86, 0x79, 0xa3, 0x21, 0xdf, 0x6a, 0x52, 0x2d,
	0x8e, 0x47, 0xbd, 0x47, 0x7e, 0x0f, 0x59, 0x8b, 0xd4, 0xf3, 0x55, 0x04, 0xe7, 0x82, 0xe5, 0x55,
	0x8a, 0xf1, 0x6a, 0x75, 0xc2, 0x9f, 0x00, 0x26, 0xb0, 0xf5, 0x23, 0x76, 0xc3, 0xbf, 0x78, 0xcd,
	0x1e, 0xd9, 0xee, 0x3c, 0x68, 0x3f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x91, 0x9f, 0xfd,
	0x6f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingServiceClient is the client API for PingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingServiceClient interface {
	Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	SendStream(ctx context.Context, opts ...grpc.CallOption) (PingService_SendStreamClient, error)
}

type pingServiceClient struct {
	cc *grpc.ClientConn
}

func NewPingServiceClient(cc *grpc.ClientConn) PingServiceClient {
	return &pingServiceClient{cc}
}

func (c *pingServiceClient) Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ping.PingService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingServiceClient) SendStream(ctx context.Context, opts ...grpc.CallOption) (PingService_SendStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PingService_serviceDesc.Streams[0], "/ping.PingService/SendStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingServiceSendStreamClient{stream}
	return x, nil
}

type PingService_SendStreamClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type pingServiceSendStreamClient struct {
	grpc.ClientStream
}

func (x *pingServiceSendStreamClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pingServiceSendStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PingServiceServer is the server API for PingService service.
type PingServiceServer interface {
	Send(context.Context, *Request) (*Response, error)
	SendStream(PingService_SendStreamServer) error
}

// UnimplementedPingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPingServiceServer struct {
}

func (*UnimplementedPingServiceServer) Send(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedPingServiceServer) SendStream(srv PingService_SendStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendStream not implemented")
}

func RegisterPingServiceServer(s *grpc.Server, srv PingServiceServer) {
	s.RegisterService(&_PingService_serviceDesc, srv)
}

func _PingService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ping.PingService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServiceServer).Send(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingService_SendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingServiceServer).SendStream(&pingServiceSendStreamServer{stream})
}

type PingService_SendStreamServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type pingServiceSendStreamServer struct {
	grpc.ServerStream
}

func (x *pingServiceSendStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pingServiceSendStreamServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ping.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _PingService_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStream",
			Handler:       _PingService_SendStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}
