runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1

#[START gae_flex_pubsub_yaml]
env_variables:
  PUBSUB_TOPIC: your-topic
  # This token is used to verify that requests originate from your
  # application. It can be any sufficiently random string.
  PUBSUB_VERIFICATION_TOKEN: your-token
#[END gae_flex_pubsub_yaml]
