# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1

#[START gae_flex_postgres_env]
env_variables:
  # See https://godoc.org/github.com/lib/pq
  #
  # Replace INSTANCE_CONNECTION_NAME with the same value as in the
  # beta_settings section below.
  POSTGRES_CONNECTION: "user=postgres password=pw dbname=db host=/cloudsql/INSTANCE_CONNECTION_NAME"
  #
  # If you're testing locally using the Cloud SQL proxy with TCP,
  # instead set this environment variable:
  # POSTGRES_CONNECTION="user=postgres password=pw dbname=db sslmode=disable"
#[END gae_flex_postgres_env]

#[START gae_flex_postgres_settings]
# Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
# For SQL v2 instances, this should be in the form of "project:region:instance".
# Cloud SQL v1 instances are not supported.
beta_settings:
  cloud_sql_instances: INSTANCE_CONNECTION_NAME
#[END gae_flex_postgres_settings]
