runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1

#[START gae_flex_postgres_env]
env_variables:
  # See https://godoc.org/github.com/lib/pq
  #
  # Replace INSTANCE_CONNECTION_NAME with the same value as in the
  # beta_settings section below.
  POSTGRES_CONNECTION: "user=postgres password=pw dbname=db host=/cloudsql/INSTANCE_CONNECTION_NAME"
  #
  # If you're testing locally using the Cloud SQL proxy with TCP,
  # instead set this environment variable:
  # POSTGRES_CONNECTION="user=postgres password=pw dbname=db sslmode=disable"
#[END gae_flex_postgres_env]

#[START gae_flex_postgres_settings]
# Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
# For SQL v2 instances, this should be in the form of "project:region:instance".
# Cloud SQL v1 instances are not supported.
beta_settings:
  cloud_sql_instances: INSTANCE_CONNECTION_NAME
#[END gae_flex_postgres_settings]
