runtime: go1.11
env: flex

runtime_config:
  operating_system: ubuntu22
  runtime_version: 1.21

# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
manual_scaling:
  instances: 1

# For applications which can take advantage of session affinity
# (where the load balancer will attempt to route multiple connections from
# the same user to the same App Engine instance), uncomment the folowing:

# network:
#   session_affinity: true
