# Copyright 2015 Google Inc. All rights reserved.
# Use of this source code is governed by the Apache 2.0
# license that can be found in the LICENSE file.
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
