runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

# [START env_variables]
env_variables:
  MJ_FROM_EMAIL: your-mailjet-sender-address
  MJ_APIKEY_PUBLIC: your-mailjet-api-key
  MJ_APIKEY_PRIVATE: your-mailjet-secret-key
# [END env_variables]
